### ISSUE TITLE
[HVQM4] Bug - Artifacts in a video file

### ISSUE THREAD

**Issue by xedmain** [librempeg/librempeg#10]
In the HVQM4 video decoder, there is a bug, due to which there are artifacts in this video file:
https://www.mediafire.com/file/r6sk6b5g8w0dogq/01010101.h4m/file
Excuse the mediafire link, the file is too big.

Frames 1116 to 1140 have these green squares (pictured frame 1116):
![output1116](https://github.com/librempeg/librempeg/assets/141858299/a84fd388-e83f-47a3-8301-7dc913d2d24b)

They are not present when played through other means (as an example, a screenshot of an emulator playing the cutscene in the original game, on the same exact frame):
![01010101_frame1119](https://github.com/librempeg/librempeg/assets/141858299/9f531015-a83a-4d04-9a3b-0cb739ed068c)

Would like to see this fixed.
Thank you for your hard work, other than this issue, seems to be almost 1:1 accurate.

**Comment by richardpl** [comment]
Looks like something is broken in motion compensation code, will inspect.
