### ISSUE TITLE
`Assertion s->nb_components == av_pix_fmt_count_planes(s->picture_ptr->format) failed at src/libavcodec/mjpegdec.c:2660` after b661a8b

### ISSUE THREAD

**Issue by debugzxcv** [librempeg/librempeg#13]
`ffmpeg -i 535725962_a.jpg -f null -`
Assertion s->nb_components == av_pix_fmt_count_planes(s->picture_ptr->format) failed at src/libavcodec/mjpegdec.c:2660

[(NSFW) 535725962_a.jpg](https://pixhost.to/show/286/535725962_a.jpg)

**Comment by richardpl** [comment]
Thanks for report.
