### ISSUE TITLE
[Question] lavfi/vsrc_testsrc: smptebars color primaries and transfer characteristics

### ISSUE THREAD

**Issue by bbgdzxng1** [librempeg/librempeg#5]
Hi Paul - I hope I have not disturbed the tranquility of your repo.  I also hope I have not breached etiquette in raising a question in this repo.

Firstly, I am not a developer, just a humble (and grateful) user and admirer of your work over the years.

I'm hoping to understand the correct colorspace, primaries and trc of the smptebars filter.  My goal is to use smptebars to test subsequent colorspace conversions, using smptebars (and its big brother smptehdbars) as a known, color-perfect 8-bit yuv input to test color conversions of other subsequent filters such as colorspace/swscale/libplacebo.  I'm hoping that as the author, you may be able to offer some guidance.

Based on my testing, I believe that the default characteristics of the smptebars test pattern are:

```
$ ffmpeg -f lavfi -i smptebars=size=ntsc:rate=ntsc,format=pix_fmts=yuv422p,showinfo,trim=end_frame=1 -f null dummy

[Parsed_showinfo] color_range:unknown color_space:bt470bg color_primaries:unknown color_trc:unknown
```

While I am not a developer, I have at least checked the source.  I understand the source sets [only the colorspace as bt470bg](https://github.com/librempeg/librempeg/blob/c1005cd1371601487cd1bdb5b0ecd426e5a5a408/libavfilter/vsrc_testsrc.c#L1521) within the avframe.  The smptebars filter does not currently set primaries/trc/range within the avframe.

My challenge is ~FFmpeg's~ librempeg's colorspace filter requires that all of range, space, primaries and trc are known (or are set within avframe with setparams), otherwise a subsequent colorspace filter will error with `Unsupported input primaries 2 (unknown)` | `Unsupported input transfer characteristics 2 (unknown)`.  I appreciate that this error from the colorspace filter can be avoided by overriding by specifying irange, iprimaries and itrc.  This, of course, assumes the user actually knows input primaries, transfer characteristics and range of the source - and for smptebars, some of these values are unknown to the user (and avframe).

Since smptebars does not currently set the primaries and transfer characteristics within avframe, as the author of smptebars, _what would you consider to be the correct values for primaries and trc_ of the smptebars source?  Since the default colorspace of smptebars is `bt470bg`, would it be appropriate to assume that the primaries and trc for smptebars are also in line with bt601-625, ie `(bt470/bt470bg/smpte170m)`?

Furthermore, in your opinion, should smptebars and smptehdbars be considered `pc` range, or should they be considered `limited` range (albeit with outlier colors)?  The current `Unknown` does leave a user with some ambiguity, which is not ideal from an end-user's perspective.

Can you also clarify whether the PAL/bt470bg colorspace is considered optimal for smptebars?  I appreciate that [EG1:1990](https://pub.smpte.org/latest/eg1/eg0001-1990_stable2004.pdf) makes no reference to colorometry, but [SMPTE RP219](https://pub.smpte.org/doc/rp219-1/20140714-pub/) states _"refer to published signal standards for HDTV and SDTV for definitions of the colorimetry relevant to the respective signal formats."_ which suggests that the most appropriate default for smptehdbars should be all of `(bt709/bt709/bt709)` and a user may infer that for the case of smptebars, a more appropriate default for smptebars would be BT.601-525 `(smpte170m/smpte170m/smpte170m)` colorometry above BT.601-625 `(bt470m/unknown/unknown)`, since both RP219 and EG1 are primarily North American test patterns.

Please be gentle if I have displayed my ignorance.  Thanks in advance.

**Comment by richardpl** [comment]
Should be fixed, recheck with proper YUV to RGB transform if colors are what you expect.

**Comment by bbgdzxng1** [comment]
Many thanks, sir.  Very cool indeed.

https://github.com/librempeg/librempeg/commit/9f39ba7be5bd4845020d5805653847e68ca8c202
https://github.com/librempeg/librempeg/commit/c9350f70670c6f3cc4b257132627b322acb5862f

**Comment by bbgdzxng1** [comment]
@haasn - on FFmpeg devel mailing list https://ffmpeg.org//pipermail/ffmpeg-devel/2024-January/320528.html, you mentioned about untagged ranges of testsrc virtual inputs.

_"The status quo of outputting *untagged* limited range YUV by default persists, as this was an intentional design choice, and it's consistent with the status quo. That said, it would be trivial to change."_

Paul kindly tweaked the testsources in the above commits for smptebars, smptehdbars, pal75bars and pal100bars in vsrc_testsrc to include updated space for smptebars/eg1:1990 and added range tags.

I thought these commits may be relevant to your comment on ffmpeg-devel.

Big thanks to Paul - it made testing classical colorspace filtering with SMPTE EG1:1990 (smptebars) and SMPTE RP219 (smptehdbars) much nicer to use from a CLI user's perspective and may be equally as relevant for other YUV, RGB and YUV+RGB capable testsources.

**Comment by haasn** [comment]
@bbgdzxng1 thanks for the heads up. The quoted section is referring to e.g. `"color"`. The *bars filters already set their colorspace and range correctly, as of the linked series.

That said, good catch about the SMPTE170M vs BT470BG. I can backport that fix on top of the above patches.

**Comment by bbgdzxng1** [comment]
@haasn - A huge thanks for _all_ your ongoing efforts around space, primaries, transfer and range across many different modules.  Every little step that helps push the project into a full colorometry-aware and correct workflow is greatly appreciated from this very dumb end user.

Since this is Paul's repo, I thank him for the SMPTE170M fix on SMPTE EG1:1990 / smptebars.

Have a great day.
