### ISSUE TITLE
Question @richardpl bout HVQM4 decoder

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [librempeg/librempeg#8]
Is it now merged into librempeg?

Couldn't find anything on this and a bro needs the video decoder as he didn't save your ffmpeg fork with  HVQM4 decoder commit , appreciated

**Comment by richardpl** [comment]
Not merged. I still have locally old branch with hvqm4 A&V decoder and demuxer and dunno for how long.

**Comment by washingleavesandthensome23-434** [comment]
Can I have I really need it

**Comment by washingleavesandthensome23-434** [comment]
> Not merged. I still have locally old branch with hvqm4 A&V decoder and demuxer and dunno for how long.

Cani I have I really need it

**Comment by DrunkRichtofen** [comment]
I'd like to second this. Even if it is not planned to be used in the future, could it at least be made available if anyone still needs it?

**Comment by Dev-LexKing** [comment]
A decoder would be a good addition to the project. If you could release this in the coming future that'd be greatly appreciated. It will help the project a lot.

**Comment by Murad58** [comment]
Would be awesome if it could be made available if possible.

**Comment by celestialnerd54** [comment]
the release could indeed make things easier for us..

**Comment by delltalal** [comment]
I personally believe that building with hvqm4 A&V decoder and demuxer would be extremely useful, hopefully it'll be made available.

**Comment by NotTsunami** [comment]
> Hello, team lead of the upscaling project here. The hvqm4 decoder is very important for us as we're striving for the best quality possible for the fans, and other tools simply won't do the job as good as the decoder you have made. Me & the team would be very thankful if it was made public again.

The patches (albeit old) still appear to relatively public, so you can try cherry-picking on top of this repo if they aren't merged back in.

https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2022-February/292964.html - `[PATCH 1/3] avcodec: add ADPCM IMA HVQM4 decoder`
https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2022-February/292965.html - `[PATCH 2/3] [WIP] avcodec: add HVQM4 Video decoder`
https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2022-February/292966.html - `[PATCH 3/3] avformat: add hvqm4 demuxer`

**Comment by NotTsunami** [comment]
> > > Hello, team lead of the upscaling project here. The hvqm4 decoder is very important for us as we're striving for the best quality possible for the fans, and other tools simply won't do the job as good as the decoder you have made. Me & the team would be very thankful if it was made public again.
> > 
> > 
> > The patches (albeit old) still appear to relatively public, so you can try cherry-picking on top of this repo if they aren't merged back in.
> > https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2022-February/292964.html - `[PATCH 1/3] avcodec: add ADPCM IMA HVQM4 decoder` https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2022-February/292965.html - `[PATCH 2/3] [WIP] avcodec: add HVQM4 Video decoder` https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2022-February/292966.html - `[PATCH 3/3] avformat: add hvqm4 demuxer`
> 
> If I remember correctly, @richardpl had made some fixes to the patches (iirc there being some artifacts when decoding) in August of 2023, while these seem to be from February of 2022, so unfortunately I'm not sure if this will help, but thank you nonetheless! Maybe there's some public post like this for the August version of the patches.

https://patchwork.ffmpeg.org/project/ffmpeg/patch/CAPYw7P6xo6PNU-MVwxDzdagDE8RPuL63DPjPqdVEjwiTfP6LcA@mail.gmail.com/ This might be what you're looking for. I _assume_ it would be applied with patch 1 and 3 of the old patchset.

**Comment by washingleavesandthensome23-434** [comment]
> Not merged. I still have locally old branch with hvqm4 A&V decoder and demuxer and dunno for how long.

Hoping ya manage to merge , we really need that commit please,  Respectfully
